#spring:
#  security:
#    user:
#      name: buzz
#      password: infinity

taco:
  orders:
    pageSize: 10


  discount:
    codes:
      abcdef: 10
    
---
spring:
  profiles: prod
  
  datasource:
    url: jdbc:mysql://localhost/pancakecloud
    username: pancakeuser
    password: pancakepassword
    
logging:
  level:
    pancake: WARN
    
